#!/bin/sh
#
# Starts Mopidy.
#

BIN=/usr/bin/mopidy
ARGS=''
PIDFILE=/var/run/mopidy.pid

start() {
	echo -n "Starting Mopidy: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec $BIN -- $ARGS
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping Mopidy: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
